// backend/src/routes/index.js
import { Router } from 'express';
import auth from './auth.routes.js';
import uploads from './upload.routes.js';
import investigadores from './investigadores.routes.js';
import investigaciones from './investigaciones.routes.js';
import publicaciones from './publicaciones.routes.js';
import noticias from './noticias.routes.js';
import contacto from './contacto.routes.js';
import instituciones from './instituciones.routes.js';
import areas from './areas.routes.js';
import tiposInvestigacion from './tipos-investigacion.routes.js';
import about from './about.routes.js';
import seguridad from './seguridad.routes.js';
import registro from './registro.routes.js';
import dashboard from './dashboard.routes.js';
import perfil from './perfil.routes.js';

const router = Router();
router.use('/auth', auth);
router.use('/upload', uploads);
router.use('/investigadores', investigadores);
router.use('/investigaciones', investigaciones);
router.use('/publicaciones', publicaciones);
router.use('/noticias', noticias);
router.use('/contacto', contacto);
router.use('/instituciones', instituciones);
router.use('/areas-conocimiento', areas);
router.use('/tipos-investigacion', tiposInvestigacion);
router.use('/about', about);
router.use('/seguridad', seguridad);
router.use('/registro', registro);
router.use('/dashboard', dashboard);
router.use('/perfil', perfil);
export default router;
