import { Router } from 'express';
import * as c from '../controllers/investigadores.controller.js';
import { auth, requirePermission } from '../middlewares/auth.js';
const r=Router();
r.get('/',c.getAll);
r.get('/admin',auth,requirePermission('investigadores','lectura'),c.getAdmin);
r.post('/',auth,requirePermission('investigadores','escritura'),c.create);
r.put('/:id',auth,requirePermission('investigadores','actualizar'),c.update);
r.delete('/:id',auth,requirePermission('investigadores','eliminar'),c.remove);
export default r;
